In [1]:
import sys
import pandas as pd
import numpy as np
import matplotlib
import scipy as sp
import sklearn

In [2]:
print("Python version: {}".format(sys.version))
print("pandas version: {}".format(pd.__version__))
print("matplotlib version: {}".format(matplotlib.__version__))
print("NumPy version: {}".format(np.__version__))
print("SciPy version: {}".format(sp.__version__))
print("scikit-learn version: {}".format(sklearn.__version__))

Python version: 3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:34:09) [GCC 12.3.0]
pandas version: 2.1.0
matplotlib version: 3.7.2
NumPy version: 1.25.2
SciPy version: 1.11.2
scikit-learn version: 1.3.0


In [3]:
## Manipulating and comparing arrays

# Arithmetic
x = np.array([[1,2,3],[4,5,6]], dtype=np.int32)


In [4]:
my_list = [1,2,3]
np.sum(my_list)

6

In [5]:
a2 = np.array([[1,2,3.3], [4,5,6.5]])
a2.reshape(2,3,1)

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [6]:
np.random.seed(0)
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [7]:
weekly_sales = pd.DataFrame(sales_amounts, index=["Mon","Tues","Wed","Thurs","Fri"], columns=["Almond butter","Peanut butter","Cashew butter"])
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [8]:
prices = np.array([10,8,12])
prices


array([10,  8, 12])

In [9]:
butter_prices = pd.DataFrame(prices.reshape(1,3), index=["Price"], columns=["Almond butter","Peanut butter","Cashew butter"])
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [10]:
total_sales = prices.reshape(1,3).dot(sales_amounts.T)
total_sales

array([[240, 138, 458, 232, 142]])

In [11]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

Mon  Tues  Wed  Thurs  Fri
Price  240   138  458    232  142

In [12]:
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total ($)
Mon               12             15              0        240
Tues               3              3              7        138
Wed                9             19             18        458
Thurs              4              6             12        232
Fri                1              6              7        142

In [13]:
weekly_sales.shape, daily_sales.T.shape

((5, 4), (5, 1))

In [14]:
random_array = np.random.randint(10, size=(3,5))
np.sort(random_array)

array([[1, 5, 7, 8, 9],
       [0, 3, 4, 8, 9],
       [0, 2, 3, 3, 5]])

In [15]:
np.argmax(random_array, axis=1)


array([4, 1, 1])

<img src="numpy-images/panda.png">

In [18]:
from matplotlib.image import imread

panda = imread("numpy-images/panda.png")
car = imread("numpy-images/car-photo.png")
dog = imread("numpy-images/dog-photo.png")
print(type(panda))

<class 'numpy.ndarray'>
